name: Feature Integration

on:
    pull_request:
        branches:
            - 'master'
            - 'contrib/**'

jobs:
    build-test-format:
        name: Build, Test & Auto-Format
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Set up JDK 25
              uses: actions/setup-java@v4
              with:
                  java-version: '25'
                  distribution: 'temurin'
                  cache: 'gradle'

            - name: Automatische Spotless-Formatierung anwenden
              run: ./gradlew :dungeon:spotlessApply

            - name: Formatierung in den Pull Request pushen
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Automatische Spotless-Formatierung"
                  commit_user_name: "GitHub Actions Bot"

            - name: Build und Test (Nur Dungeon)
              run: ./gradlew :dungeon:assemble :dungeon:test
